# Generated by Django 2.2.6 on 2019-12-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='hasAc',
            field=models.BooleanField(default=True),
        ),
    ]
