# Generated by Django 2.2.6 on 2019-12-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0002_bus_hasac'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='total_seat',
            field=models.IntegerField(default=40),
        ),
    ]
