# Generated by Django 2.2.6 on 2019-12-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0003_bus_total_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='coachNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='fare',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
