# Generated by Django 2.2.6 on 2019-12-09 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0005_trip_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
