# Generated by Django 2.2.6 on 2019-12-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0006_auto_20191209_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='type',
        ),
        migrations.AddField(
            model_name='bus',
            name='Class',
            field=models.CharField(choices=[('ECONOMY', 'Economy Class'), ('BUSINESS', 'Business Class')], default='ECONOMY', max_length=10),
        ),
        migrations.AddField(
            model_name='bus',
            name='manufacturer',
            field=models.CharField(choices=[('SCANIA', 'Scania'), ('VOLVO', 'Volvo'), ('HYUNDAI', 'Hyundai'), ('HINO', 'Hino'), ('MAN', 'Man')], default='HINO', max_length=10),
        ),
    ]
