# Generated by Django 2.2.6 on 2019-12-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0007_auto_20191209_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_station',
            field=models.CharField(choices=[('DHAKA', 'Dhaka'), ('CHATTAGRAM', 'Chattagram'), ('BARISAL', 'Barisal'), ('SYLHET', 'Sylhet'), ('KHULNA', 'Khulna')], default='...', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_station',
            field=models.CharField(choices=[('DHAKA', 'Dhaka'), ('CHATTAGRAM', 'Chattagram'), ('BARISAL', 'Barisal'), ('SYLHET', 'Sylhet'), ('KHULNA', 'Khulna')], default='...', max_length=20),
        ),
    ]
