# Generated by Django 2.2.6 on 2019-12-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0008_auto_20191209_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
