# Generated by Django 2.2.6 on 2019-12-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0009_auto_20191209_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_id',
        ),
        migrations.AddField(
            model_name='trip',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
