# Generated by Django 2.2.6 on 2019-12-10 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0010_auto_20191209_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_rows', models.IntegerField(default=10)),
                ('num_of_columns', models.IntegerField(default=4)),
                ('column_in_first_row', models.IntegerField(default=4)),
                ('column_in_last_row', models.IntegerField(default=5)),
                ('A1', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('A2', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('A3', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('A4', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('B1', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('B2', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('B3', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('B4', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('C1', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('C2', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('C3', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('C4', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('D1', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('D2', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('D3', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('D4', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('E1', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('E2', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('E3', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('E4', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('F1', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('F2', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('F3', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('F4', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('G1', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('G2', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('G3', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('G4', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('H1', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('H2', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('H3', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('H4', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('I1', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('I2', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('I3', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('I4', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('J1', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('J2', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('J3', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('J4', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
                ('J5', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busTicketBooking.Seat'),
        ),
    ]
