# Generated by Django 2.2.6 on 2019-12-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0011_auto_20191210_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='total_seat',
        ),
        migrations.AddField(
            model_name='seat',
            name='total_seat',
            field=models.IntegerField(default=40),
        ),
    ]
