# Generated by Django 2.2.6 on 2020-01-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0013_auto_20200102_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='operator_name',
            field=models.CharField(choices=[('Hanif', 'Hanif'), ('Green Line', 'Green Line'), ('Tungipara Express', 'Tungipara Express'), ('Saintmartin Hyundai', 'Saintmartin Hyundai')], default='...', max_length=20),
        ),
    ]
