# Generated by Django 2.2.6 on 2020-01-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0014_auto_20200102_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='coach',
        ),
        migrations.AddField(
            model_name='trip',
            name='coach_no',
            field=models.IntegerField(default=100),
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
