# Generated by Django 2.2.6 on 2020-01-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0016_trip_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='manufacturer',
            field=models.CharField(choices=[('SCANIA', 'Scania'), ('VOLVO', 'Volvo'), ('HYUNDAI', 'Hyundai'), ('HINO', 'Hino'), ('MAN', 'Man')], default='HINO', max_length=50),
        ),
        migrations.AlterField(
            model_name='bus',
            name='operator_name',
            field=models.CharField(choices=[('Hanif', 'Hanif'), ('Green Line', 'Green Line'), ('Tungipara Express', 'Tungipara Express'), ('Saintmartin Hyundai', 'Saintmartin Hyundai')], default='...', max_length=50),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_no',
            field=models.CharField(default='A1', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(choices=[('DHAKA', 'Dhaka'), ('CHATTAGRAM', 'Chattagram'), ('BARISAL', 'Barisal'), ('SYLHET', 'Sylhet'), ('KHULNA', 'Khulna')], default='...', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_station',
            field=models.CharField(choices=[('DHAKA', 'Dhaka'), ('CHATTAGRAM', 'Chattagram'), ('BARISAL', 'Barisal'), ('SYLHET', 'Sylhet'), ('KHULNA', 'Khulna')], default='...', max_length=50),
        ),
        migrations.AlterField(
            model_name='tripseat',
            name='seat_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tripseat',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('BOOKED', 'Booked'), ('DISABLED', 'Disabled')], default='...', max_length=50),
        ),
    ]
