# Generated by Django 2.2.6 on 2020-01-19 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0017_auto_20200105_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'M'), ('FEMALE', 'F'), ('OTHER', 'O')], max_length=10)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BD')),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_time', models.DateTimeField(default=datetime.datetime.now)),
                ('num_of_booked_seat', models.IntegerField(default=1)),
                ('total_fare', models.IntegerField(default=0)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busTicketBooking.Passenger')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busTicketBooking.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busTicketBooking.Reservation')),
            ],
        ),
    ]
